### ISSUE TITLE
Please implement isProperSubdir()

### ISSUE THREAD

**Issue by rulatir** [zkochan/packages#123]
[edited to revise the request in light of correct understanding of the current behavior]

As per title, please implement `isProperSubdir()` which would only return `true` if the second parameter is a proper subdirectory of the first but not the same. This should be in the library because it should use the same path normalization/resolution strategy as the original function.

Alternatively we could add an optional boolean third argument to turn on the `!==` check, defaulting to `false`.

Implementation should be trivial and I could submit a PR, but please decide on the API variant.

**Comment by zkochan** [comment]
isSubdir already works as isSubdirOrSame

**Comment by rulatir** [comment]
Thanks for a prompt response. I revised my request.

**Comment by zkochan** [comment]
I'd probably name it `isSubdirStrict`

or maybe we can make a breaking change and add `isSubdirOrSame`

**Comment by rulatir** [comment]
Did preliminary PR, but really all the work is in deciding how to name things.

**Comment by rulatir** [comment]
The solution I propose makes it possible to access the new API without modifying the import/require statement. I add the reference to the new function as a property of the old function. Usage:

```javascript
isSubdir = require('is-subdir');
if (isSubdir.proper(dir1, dir2)) {
   //...
}
```

Rename to `strict`?

**Comment by zkochan** [comment]
ok

**Comment by rulatir** [comment]
A sec to update README.md and tests...

**Comment by rulatir** [comment]
PR ready with updated test, README.md and `is-subdir/index.d.ts`.

**Comment by zkochan** [comment]
ok, but you need to submit the PR to this repo

**Comment by rulatir** [comment]
Oops. #124 is ready.

**Comment by zkochan** [comment]
published
