### ISSUE TITLE
rename-overwrite@5.0.1 version make existing projects fails based on old node npm versions

### ISSUE THREAD

**Issue by alexander-schranz** [zkochan/packages#194]
We are using `symlink-dir` package to create symlinks. Increasing the required node version inside this project in a patch / minor release make this now break.

We try to execute:

```
npx "symlink-dir@<6.0" ../../vendor node_modules/@sulu/vendor
```

Which ends now on Node 14 and 16 as our project requires strict engines with:

```
npm ERR! notsup Unsupported engine for rename-overwrite@5.0.1: wanted: {"node":">=18"} (current: {"node":"14.21.3","npm":"6.14.18"}
```

Best way for our case would be to revert the requirement changes of  5.0.1 and release a version 5.0.2 without them and release a new major with the new node npm requirements.

**Comment by zkochan** [comment]
done

**Comment by alexander-schranz** [comment]
Thank you!
